import "./globals.css";
import Layout from "@/component/Layout";


export const metadata = {
  title: "Bijan Food industries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" dir="rtl">
    
      <body >
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
